development:
  adapter: postgresql
  encoding: unicode
  database: regex_hero_dev
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: regex_hero_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: regex_hero_production
  pool: 5
  username: teacup
  password: